### ISSUE TITLE
slaves

### ISSUE THREAD

**Issue by PKostya** [alexholmes/vagrant-hadoop-2.7.1-spark-1.4.1-hive-1.2.1#1]
Hi, please add few slaves like in original version 
thanks

**Comment by ghost** [comment]
Hello,
I am trying to pull the data from s3 to run the spark jobs but it fails when using the VM.

Could you please update the setting the Vm so that we would be able to pull the data from s3.

Thanks

**Comment by alexholmes** [comment]
Hi,

My goal here was to create a single VM which targets HDFS.  Feel free to fork and modify if you want to support multiple VM's or target S3.

Thanks,
Alex
